name: Go

on:
  create:
    tags:
      - v3*
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1

    - name: Set up Env
      run: echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: runner.os−go−{ { hashFiles('**/go.sum') } }
        restore-keys: ${{ runner.os }}-go-        

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
    - name: Deploy Windows
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist/m7s_${{ env.version }}_windows_amd64.tar.gz
        remote: /opt/dexter/windows.tgz
        host: monibuca.com
        username: root
        privateKey: ${{ secrets.PEM }}

    - name: Deploy Mac
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist/m7s_${{ env.version }}_darwin_amd64.tar.gz
        remote: /opt/dexter/mac.tgz
        host: monibuca.com
        username: root
        privateKey: ${{ secrets.PEM }}		  

    - name: Deploy Mac arm64
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist/m7s_${{ env.version }}_darwin_arm64.tar.gz
        remote: /opt/dexter/mac_arm64.tgz
        host: monibuca.com
        username: root
        privateKey: ${{ secrets.PEM }}		        

    - name: Deploy Linux
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist/m7s_${{ env.version }}_linux_amd64.tar.gz
        remote: /opt/dexter/linux.tgz
        host: monibuca.com
        username: root
        privateKey: ${{ secrets.PEM }}

    - name: Deploy Linux arm64
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist/m7s_${{ env.version }}_linux_arm64.tar.gz
        remote: /opt/dexter/linux_arm64.tgz
        host: monibuca.com
        username: root
        privateKey: ${{ secrets.PEM }}        
        
         
